#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 2
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle false
bspc config window_gap 5

# rules
bspc rule -a feh state=floating

# launch wallpapers
feh -q --bg-scale ~/Pictures/Wallpapers/1.jpg &
# launch polybar
~/.config/polybar/launch.sh &
# launch notification daemon
dunst -config ~/.config/dunst/dunstrc &
# TODO maybe later add redshift
# pgrep -x redshift > /dev/null || redshift &
# start compositor
~/.config/picom/launch.sh &
# Screenshot tool
flameshot &
setxkbmap -option caps:ctrl_modifier &
